### ISSUE TITLE
cert_create: strdup from string.h is defined as static function in src/main.c

### ISSUE THREAD

**Issue by bcran** [TrustedFirmware-A/trusted-firmware-a#10] opened 2024-05-23 15:06 UTC
In tools/cert_create/src/main.c. a static function `strdup` is defined, but the same function is already declared non-static in string.h. This causes a build failure on FreeBSD.

**Comment by odeprez** [comment] 2024-08-26 08:45
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224

**Comment by ManishVB-Arm** [comment] 2024-09-03 14:37
This patch is merged https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/30224. Please let me know your observation.

**Comment by odeprez** [comment] 2024-09-12 11:25
Closing the ticket as the issue is hopefully resolved by Manish's change.

**Closed by odeprez** 2024-09-12 11:25 UTC
